# Generated by Django 4.2 on 2025-12-14 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LearningPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_description', models.TextField()),
                ('developer_level', models.CharField(max_length=50)),
                ('framework', models.CharField(blank=True, max_length=100)),
                ('software_type', models.CharField(max_length=100)),
                ('plan_data', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('session_key', models.CharField(blank=True, db_index=True, max_length=100)),
            ],
            options={
                'verbose_name': 'Learning Plan',
                'verbose_name_plural': 'Learning Plans',
                'ordering': ['-created_at'],
            },
        ),
    ]
