# Generated by Django 4.2 on 2025-12-15 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avatar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character_class', models.CharField(max_length=50)),
                ('profession', models.CharField(max_length=100)),
                ('original_image', models.ImageField(blank=True, null=True, upload_to='avatars/original/')),
                ('generated_avatar', models.ImageField(upload_to='avatars/generated/')),
                ('session_key', models.CharField(blank=True, db_index=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Avatar',
                'verbose_name_plural': 'Avatars',
                'ordering': ['-created_at'],
            },
        ),
    ]
