# Generated by Django 4.2 on 2025-12-15 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0002_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('company_name', models.CharField(blank=True, max_length=200)),
                ('job_title', models.CharField(blank=True, max_length=100)),
                ('additional_info', models.TextField(blank=True, help_text='Any additional information provided by the user')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session_key', models.CharField(blank=True, db_index=True, max_length=100)),
            ],
            options={
                'verbose_name': 'Wishlist Signup',
                'verbose_name_plural': 'Wishlist Signups',
                'ordering': ['-created_at'],
            },
        ),
    ]
