# Generated by Django 4.2 on 2025-12-15 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0003_wishlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_text', models.TextField()),
                ('email', models.EmailField(blank=True, help_text='Optional email if user provides it', max_length=254, null=True)),
                ('name', models.CharField(blank=True, help_text='Optional name if user provides it', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session_key', models.CharField(blank=True, db_index=True, max_length=100)),
            ],
            options={
                'verbose_name': 'Feedback',
                'verbose_name_plural': 'Feedback Entries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PartnerInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('company_name', models.CharField(blank=True, max_length=200)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('message', models.TextField(blank=True, help_text='Optional message from partner')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session_key', models.CharField(blank=True, db_index=True, max_length=100)),
            ],
            options={
                'verbose_name': 'Partner Interest',
                'verbose_name_plural': 'Partner Interests',
                'ordering': ['-created_at'],
            },
        ),
    ]
