# Generated by Django 4.2 on 2025-12-15 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0004_feedback_partnerinterest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='name',
            field=models.CharField(blank=True, help_text='Optional name if user provides it', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='partnerinterest',
            name='company_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='partnerinterest',
            name='message',
            field=models.TextField(blank=True, help_text='Optional message from partner', null=True),
        ),
        migrations.AlterField(
            model_name='partnerinterest',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
